### ISSUE TITLE
Both :Telescope and :lua ... throw errors

### ISSUE THREAD

**Issue by sh-cau** [lrfurtado/telescope-gitlab.nvim#1]
Running `:Telescope gitlab issues` throws

> E5108: Error executing lua ...lescope-gitlab.nvim/lua/telescope/_extensions/gitlab.lua:113: Expected value but found T_END at character 1
stack traceback:
        [C]: in function 'decode'
        ...lescope-gitlab.nvim/lua/telescope/_extensions/gitlab.lua:113: in function 'issues'
        [string ":lua"]:1: in main chunk

Running `:lua require('telescope').extensions.gitlab.issues({fields={state="opened"}})` throws

>Error executing Lua callback: ...lescope-gitlab.nvim/lua/telescope/_extensions/gitlab.lua:113: Expected value but found T_END at character 1
stack traceback:
        [C]: in function 'decode'
        ...lescope-gitlab.nvim/lua/telescope/_extensions/gitlab.lua:113: in function <...lescope-gitlab.nvim/lua/telescope/_extensions/gitlab.lua:88>
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:183: in function 'run_command'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>

I am using glab version `1.35.0`, neovim version `0.9.1`, installed the plugin using Lazy.

PS: Opening a terminal from nvim in a gitlab repo and running `glab issue list` works fine.

**Comment by sh-cau** [comment]
My bad, I did not have JQ installed...

**Comment by lrfurtado** [comment]
interesting I thought I had logic where it would check for existance of jq. Do you have the latest code ? 
<img width="493" alt="image" src="https://github.com/lrfurtado/telescope-gitlab.nvim/assets/943194/264920f2-3692-42fa-b48f-41cbd1798052">

**Comment by lrfurtado** [comment]
thanks fir using the extension by the way.

**Comment by sh-cau** [comment]
I do have the latest version but this error message did not appear.

**Comment by lrfurtado** [comment]
I get the error message on startup when jq is not on path 
![image](https://github.com/lrfurtado/telescope-gitlab.nvim/assets/943194/d7192bd6-e810-4b86-9ec5-eebbf5f1f636)

**Comment by sh-cau** [comment]
When I remove jq again, I do get this error message. I guess I just happened to miss it.
